language: go

go:
  - "1.10.x"

if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script: make test

notifications:
  email: false

after_success:
  - chmod +x ./scripts/notif.sh
  - ./scripts/notif.sh success
after_failure:
  - chmod +x ./scripts/notif.sh
  - ./scripts/notif.sh failure
