language: go

go:
  - "1.10.x"

branches:
  only:
    - master

script: make test

notifications:
  email: false

after_success:
  - ./scripts/notif.sh success
after_failure:
  - ./scripts/notif.sh failure